Adding log4J xml for CT
ExpediaGroup/apiary-shuntingyard-docker pull request #9
Opened 2020-03-30 16:14 UTC by abhimanyugupta07

2020-03-30 16:21 UTC, massdosage requested changes

2020-03-30 16:21 UTC, massdosage commented on CHANGELOG.md
> +## [2.1.1] - TBD
Let's make it 2.2.0 as it's more like a new feature than a bug fix.

2020-03-30 16:21 UTC, massdosage commented on CHANGELOG.md
> +- Log4j Xml for internal Circus Train instance.
```suggestion
- Log4j XML for internal Circus Train instance.
```

2020-03-31 09:25 UTC, max-jacobs approved these changes

2020-03-31 12:57 UTC, massdosage approved these changes

2020-03-31 14:54 UTC, merged